# GitGuardian Configuration
# https://docs.gitguardian.com/internal-monitoring/integrations/git_hooks/pre_commit

# Paths to scan
paths-ignore:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/venv/**"
  - "**/.venv/**"
  - "**/coverage/**"
  - "**/.git/**"
  - "**/package-lock.json"
  - "**/yarn.lock"
  - "**/pnpm-lock.yaml"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/dist/**"

# Minimum secret length (default: 20)
min-secret-length: 20

# Show progress
verbose: true

# Exit code behavior
exit-zero: false  # Fail if secrets are found

# Ignore specific patterns (add your own if needed)
# ignore:
#   - "**/test-data/**"
#   - "**/fixtures/**"
