# GitGuardian Configuration v2
# https://docs.gitguardian.com/internal-monitoring/integrations/git_hooks/pre_commit

version: 2

# Secret scanning configuration
secret:
  # Paths to ignore during scanning
  ignored-paths:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/venv/**"
    - "**/.venv/**"
    - "**/coverage/**"
    - "**/.git/**"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/pnpm-lock.yaml"
    - "**/*.min.js"
    - "**/*.min.css"

  # Minimum secret length (default: 20)
  min-secret-length: 20

  # Ignore specific secret matches (add your own if needed)
  # ignored-matches:
  #   - name: "Test API Key"
  #     match: "test_api_key_12345"

# Ignore specific patterns (add your own if needed)
# ignore:
#   - "**/test-data/**"
#   - "**/fixtures/**"
