export const USAGE_LIMITS = {
  MAX_LINKS_PER_USER: parseInt(process.env.MAX_LINKS_PER_USER || '1000', 10),
  MAX_PAGE_SIZE_BYTES: parseInt(process.env.MAX_PAGE_SIZE_BYTES || '524288', 10), // 0.5MB
  RATE_LIMIT_REQUESTS_PER_MINUTE: parseInt(process.env.RATE_LIMIT_REQUESTS_PER_MINUTE || '60', 10),
  MAX_TAG_LENGTH: 50,
  MAX_TAGS_PER_LINK: 20,
  MAX_TITLE_LENGTH: 500,
  MAX_DESCRIPTION_LENGTH: 2000,
} as const;
