services:
  - type: web
    name: smartrack-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: MAX_LINKS_PER_USER
        value: 1000
      - key: MAX_PAGE_SIZE_BYTES
        value: 524288
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 60
